export const audioPresetDummy = [
  {
    _id: "74973962",
    station_id: "fsrwrtesrd",
    title: "Nami is legend",
    tag: "INFO",
    languages: ["en", "hi", "ur", "mr"],
    original_text: "Arrival on 9 PM",
    audio_url: "./song.mp3",
  },
  {
    _id: "74973962",
    station_id: "fsrwrtesrd",
    title: "Nami is legend",
    tag: "INFO",
    languages: ["en", "hi", "ur", "mr"],
    original_text: "Arrival on 9 PM",
    audio_url: "./song.mp3",
  },
  {
    _id: "74973962",
    station_id: "fsrwrtesrd",
    title: "Nami is legend",
    tag: "INFO",
    languages: ["en", "hi", "ur", "mr"],
    original_text: "Arrival on 9 PM",
    audio_url: "./song.mp3",
  },
  {
    _id: "74973962",
    station_id: "fsrwrtesrd",
    title: "Nami is legend",
    tag: "INFO",
    languages: ["en", "hi", "ur", "mr"],
    original_text: "Arrival on 9 PM",
    audio_url: "./song.mp3",
  },
  {
    _id: "74973962",
    station_id: "fsrwrtesrd",
    title: "Nami is legend",
    tag: "INFO",
    languages: ["en", "hi", "ur", "mr"],
    original_text: "Arrival on 9 PM",
    audio_url: "./song.mp3",
  },
  {
    _id: "74973962",
    station_id: "fsrwrtesrd",
    title: "Nami is legend",
    tag: "INFO",
    languages: ["en", "hi", "ur", "mr"],
    original_text: "Arrival on 9 PM",
    audio_url: "./song.mp3",
  },
  {
    _id: "74973962",
    station_id: "fsrwrtesrd",
    title: "Nami is legend",
    tag: "INFO",
    languages: ["en", "hi", "ur", "mr"],
    original_text: "Arrival on 9 PM",
    audio_url: "./song.mp3",
  },
  {
    _id: "74973962",
    station_id: "fsrwrtesrd",
    title: "Nami is legend",
    tag: "INFO",
    languages: ["en", "hi", "ur", "mr"],
    original_text: "Arrival on 9 PM",
    audio_url: "./song.mp3",
  },
];

export const modalStyle = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: 400,
  bgcolor: 'background.paper',
  boxShadow: 24,
  p: 4,
  borderRadius:3
};